import { useState } from 'react';
import ColorPicker from './ColorPicker';
import GradientGenerator from './GradientGenerator';
import ParticleCanvas from './ParticleCanvas';

export default function ColorFlowDemo({ onClose }) {
  const [activeTab, setActiveTab] = useState('palette');
  
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Full-screen background overlay */}
      <div 
        className="absolute inset-0 bg-slate-900/95 backdrop-blur-sm" 
        onClick={onClose} 
      />
      
      {/* Full-screen modal container */}
      <div className="relative bg-gradient-to-br from-slate-800 to-slate-900 rounded-2xl w-full max-w-6xl h-[90vh] overflow-hidden border border-slate-700/50 shadow-2xl">
        {/* Header with gradient background */}
        <div className="p-6 border-b border-slate-700/50 bg-gradient-to-r from-slate-800 to-slate-900 flex justify-between items-center">
          <div>
            <h2 className="text-2xl font-bold flex items-center gap-3">
              <span className="text-3xl">🎨</span>
              <span className="bg-gradient-to-r from-cyan-400 to-blue-400 bg-clip-text text-transparent">
                ColorFlow - Interactive Palette Generator
              </span>
            </h2>
            <p className="text-slate-400 text-sm mt-1">Create, explore, and export beautiful color combinations</p>
          </div>
          <button 
            onClick={onClose}
            className="p-2 hover:bg-slate-700/50 rounded-lg text-xl transition-all hover:scale-110 hover:text-cyan-400"
          >
            ✕
          </button>
        </div>
        
        {/* Tabs - Improved styling */}
        <div className="flex border-b border-slate-700/50 bg-slate-800/50">
          {['palette', 'gradient', 'particles'].map(tab => (
            <button
              key={tab}
              className={`px-6 py-4 font-medium transition-all duration-300 flex-1 ${
                activeTab === tab 
                  ? 'border-b-2 border-cyan-400 text-cyan-400 bg-slate-800/30' 
                  : 'text-slate-400 hover:text-slate-300 hover:bg-slate-700/30'
              }`}
              onClick={() => setActiveTab(tab)}
            >
              <div className="flex items-center justify-center gap-2">
                <span className="text-lg">
                  {tab === 'palette' ? '🎨' : tab === 'gradient' ? '🌈' : '✨'}
                </span>
                {tab.charAt(0).toUpperCase() + tab.slice(1)}
              </div>
            </button>
          ))}
        </div>
        
        {/* Main content area - Takes most of the space */}
        <div className="h-[calc(90vh-180px)] overflow-y-auto p-6">
          <div className="max-w-4xl mx-auto">
            {activeTab === 'palette' && <ColorPicker />}
            {activeTab === 'gradient' && <GradientGenerator />}
            {activeTab === 'particles' && <ParticleCanvas />}
          </div>
        </div>
        
        {/* Footer with action buttons */}
        <div className="p-6 border-t border-slate-700/50 bg-gradient-to-r from-slate-800/50 to-slate-900/50">
          <div className="flex justify-between items-center max-w-4xl mx-auto">
            <div className="text-sm text-slate-400">
              <span className="flex items-center gap-2">
                <span className="w-2 h-2 bg-green-400 rounded-full animate-pulse"></span>
                Interactive Demo - Click and drag to explore
              </span>
            </div>
            <div className="flex gap-4">
              <button 
                className="px-6 py-3 border border-slate-600 rounded-lg font-semibold hover:bg-slate-700 transition-all hover:border-cyan-400/50"
                onClick={() => {
                  const colors = ['#FF6B6B', '#4ECDC4', '#FFD166', '#06D6A0', '#118AB2'];
                  navigator.clipboard.writeText(`Colors: ${colors.join(', ')}\n\nGenerated by ColorFlow Demo`);
                  alert('🎨 Default palette copied to clipboard!');
                }}
              >
                Copy Colors
              </button>
              <button 
                className="px-6 py-3 bg-gradient-to-r from-cyan-500 to-blue-500 rounded-lg font-semibold hover:from-cyan-600 hover:to-blue-600 transition-all transform hover:scale-105 shadow-lg shadow-cyan-500/20"
                onClick={onClose}
              >
                Close Demo
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}